# Generated by Django 5.1.7 on 2025-03-08 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='sobre',
        ),
    ]
