# Generated by Django 5.1.7 on 2025-03-08 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_remove_empresa_sobre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='descricao',
            new_name='sobre',
        ),
    ]
