# Generated by Django 5.1.7 on 2025-03-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_alter_pedido_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pago',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('producao', 'Produção'), ('pronto', 'Pronto para entrega'), ('entregue', 'Finalizado')], max_length=100, null=True),
        ),
    ]
