# Generated by Django 5.1.7 on 2025-03-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_pedido_pago_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('producao', 'Produção'), ('pronto', 'Pronto para entrega'), ('entregue', 'Finalizado')], default='pendente', max_length=100, null=True),
        ),
    ]
