# Generated by Django 5.1.7 on 2025-03-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_pedido_data_entrega_alter_pedido_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(blank=True, choices=[('0-pendente', 'Pendente'), ('1-producao', 'Produção'), ('2-pronto', 'Pronto para entrega'), ('3-entregue', 'Finalizado')], default='0-pendente', max_length=100, null=True),
        ),
    ]
