# Generated by Django 5.1.7 on 2025-03-14 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0010_pedido_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
            preserve_default=False,
        ),
    ]
