# Generated by Django 5.1.7 on 2025-03-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0011_pedido_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(default=208, max_length=100),
            preserve_default=False,
        ),
    ]
