# Generated by Django 5.1.7 on 2025-03-17 17:09

import empresa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0012_empresa_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=empresa.models.rename_logo),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
