# Generated by Django 5.1.7 on 2025-03-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0013_alter_empresa_logo_alter_pedido_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
