# Generated by Django 5.1.7 on 2025-03-20 19:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0015_alter_pedido_cliente_alter_pedido_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alteracoes', models.JSONField()),
                ('data_alteracao', models.DateTimeField(default=django.utils.timezone.now)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='empresa.pedido')),
            ],
        ),
    ]
